### ISSUE TITLE
Error : SdkWebViewActivityNew has leaked window

### ISSUE THREAD

**Issue by vkpdeveloper** [payu-intrepos/PayUMoney-Android-SDK#9]
Hi, Dear Developer I am implementing PayUMoney Android SDK in my app which I have done successfully but after making payment when activity give the result back I got an error which is 

`E/WindowManager(31535): android.view.WindowLeaked: Activity com.payumoney.core.SdkWebViewActivityNew has leaked window DecorView@5ff5344[SdkWebViewActivityNew] that was originally added here
E/WindowManager(31535): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:597)
E/WindowManager(31535): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:377)
E/WindowManager(31535): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
E/WindowManager(31535): 	at android.app.Dialog.show(Dialog.java:342)
E/WindowManager(31535): 	at com.payumoney.core.SdkWebViewActivityNew.c(SourceFile:485)
E/WindowManager(31535): 	at com.payumoney.core.SdkWebViewActivityNew.onResume(SourceFile:361)
E/WindowManager(31535): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
E/WindowManager(31535): 	at android.app.Activity.performResume(Activity.java:7939)
E/WindowManager(31535): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
E/WindowManager(31535): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
E/WindowManager(31535): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
E/WindowManager(31535): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/WindowManager(31535): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/WindowManager(31535): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/WindowManager(31535): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/WindowManager(31535): 	at android.os.Looper.loop(Looper.java:214)
E/WindowManager(31535): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/WindowManager(31535): 	at java.lang.reflect.Method.invoke(Native Method)
E/WindowManager(31535): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/WindowManager(31535): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

I am using test payment option with my test creds.
Same error which UPI and Card

Thank You.

**Comment by Rahul-Hooda** [comment]
@vkpdeveloper - This must be a warning and shouldn't block your payment journey. However, we will take it as a feedback and try to incorporate it in next release. If you have any other query or issue, please write to us at mobile.integration@payu.in

**Comment by jimmytrivedi** [comment]
The exact use case: Suppose I choose UPI option, I entered UPI and it got verified, now I've a PayU activity (not dialog), and in that written: "Please switch to your app..bla bla" now I haven't switched, instead I pressed back button, so pay alert dialog asked, whether I want to cancel transaction or not. I said yes, and I came back to my main activity from where I started this flow. So while cancel transaction and coming back at that time this is happening.

**Comment by jimmytrivedi** [comment]
@Rahul-Hooda This is not a warning, this is a wrong implementation. Check my above comment.
@vkpdeveloper Have you find any solution?

**Comment by vkpdeveloper** [comment]
@jimmytrivedi It is an issue from the SDK code. We can't solve this thing by our side for solving this we have to play around the SDK code.

@Rahul-Hooda Please try to fix this.

**Comment by jimmytrivedi** [comment]
@vkpdeveloper I know that this is SDK issue. That's why I'm thinking that why this is **marked as closed** without fixing it? Anyway I created new one!

BTW, Can I get your app where you integrated this PayU gateway? I just want to check the flow on UI!

**Comment by vkpdeveloper** [comment]
@jimmytrivedi I created a plugin for Flutter using Payu SDK that you can check out at https://pub.dev/packages/payu_money_flutter

You can go to my repo from here and by going to android folder you can see the implementation ok.

**Comment by jimmytrivedi** [comment]
@vkpdeveloper Thank you so much.

**Comment by dev-paradigms** [comment]
E/WindowManager: android.view.WindowLeaked: Activity com.payumoney.sdkui.ui.activities.PayUmoneyActivity has leaked window DecorView@ce003cb[PayUmoneyActivity] that was originally added here


Same issue by sdk side

**Comment by ynagarjuna2012** [comment]
```
android.view.WindowLeaked: Activity com.payu.upisdk.upiintent.PaymentResponseUpiSdkActivity has leaked window DecorView@4704640[PaymentResponseUpiSdkActivity] that was originally added here
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:816)
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:786)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:411)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:110)
                                                                                                    	at android.app.Dialog.show(Dialog.java:340)
                                                                                                    	at com.payu.upisdk.upiintent.d.c(SourceFile:11)
                                                                                                    	at com.payu.upisdk.upiintent.d.b(SourceFile:1)
                                                                                                    	at com.payu.upisdk.upiintent.PaymentResponseUpiSdkActivity.onCreate(SourceFile:120)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8006)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7990)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3584)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:233)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8010)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

Using UPI Sdk version : 1.6.14
